blank_issues_enabled: true
contact_links:
  - name: ðŸ—£ Ask a Question
    url: https://stackoverflow.com/questions/ask?tags=kuzzle
    about: How does X work?
  - name: ðŸ‘‹ Join us on Discord
    url: http://join.discord.kuzzle.io/
    about: I made this! I have an idea...
  - name: ðŸ“– Read our Documentation
    url: https://docs.kuzzle.io
    about: How to use Kuzzle?