kuzzle:
  image: kuzzleio/dev
  command: /run-debug.sh
  volumes:
    - "..:/var/app"
  ports:
    - "7511:7511"
    - "7512:7512"
    - "8080:8080"
    - "8081:8081"
  links:
    - rabbit
    - elasticsearch
    - redis
  environment:
    - MQ_BROKER_ENABLED=1
    - LIKE_A_VIRGIN
    - DEFAULT_MAPPING
    - FEATURE_COVERAGE
    - FIXTURES=/var/app/features/fixtures/empty.json

rabbit:
  image: kuzzleio/rabbitmq
  ports:
    - "61613:61613"
    - "1883:1883"
    - "5672:5672"
    - "15672:15672"

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.2
