version: '2'

services:
  proxy:
    image: kuzzleio/proxy:develop
    ports:
      - "7512:7512"

  kuzzle:
    image: kuzzleio/dev
    command: sh -c 'chmod 755 /run.sh && /run.sh'
    volumes:
      - "..:/var/app"
      - "./scripts/run-dev.sh:/run.sh"
      - "./config/pm2-dev.json:/config/pm2.json"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - proxy
      - redis
      - elasticsearch
    ports:
      - "8080:8080"
      - "9229:9229"
    environment:
      - kuzzle_services__db__host=elasticsearch
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_services__proxyBroker__host=proxy
      - NODE_ENV=development
      - DEBUG=kuzzle:*
      - DEBUG_DEPTH=0
      - DEBUG_MAX_ARRAY_LENGTH=100
      - DEBUG_EXPAND=off
      - DEBUG_SHOW_HIDDEN=on
      - DEBUG_COLORS=on

  redis:
    image: redis:3.2

  elasticsearch:
    image: elasticsearch:5.1
