version: '3'

services:
  proxy:
    image: kuzzleio/proxy
    ports:
      - "7513:7512"

  kuzzle:
    image: kuzzleio/dev
    command: sh -c 'chmod 755 /run.sh && /run.sh'
    volumes:
      - "..:/var/app"
      - "./scripts/run-dev.sh:/run.sh"
      - "./config/pm2-dev.json:/config/pm2.json"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - redis
      - elasticsearch
    ports:
      - "7512:7512"
      - "9229:9229"
    environment:
      - kuzzle_services__db__client__host=http://elasticsearch:9200
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_server__entryPoints__proxy=true
      - kuzzle_server__proxy__host=proxy
      - NODE_ENV=${NODE_ENV:-development}
    # - DEBUG=${DEBUG:-kuzzle:*}
      - DEBUG=${DEBUG:-none}
      - DEBUG_DEPTH=${DEBUG_DEPTH:-0}
      - DEBUG_MAX_ARRAY_LENGTH=${DEBUG_MAX_ARRAY:-100}
      - DEBUG_EXPAND=${DEBUG_EXPAND:-off}
      - DEBUG_SHOW_HIDDEN={$DEBUG_SHOW_HIDDEN:-on}
      - DEBUG_COLORS=${DEBUG_COLORS:-on}

  redis:
    image: redis:3.2

  elasticsearch:
    image: kuzzleio/elasticsearch:5.4.1
    environment:
      - cluster.name=kuzzle
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

