kuzzle:
  image: kuzzleio/kuzzle
  volumes:
    - "..:/var/app"
    - "/var/log"
  ports:
    - "7511:7511"
    - "7512:7512"
  command: /run-perf.sh
  links:
    - rabbit
    - elasticsearch
    - redis
  environment:
    - MQ_BROKER_ENABLED
    - LIKE_A_VIRGIN
    - DEFAULT_MAPPING
    - FIXTURES
    - FEATURE_COVERAGE

rabbit:
  image: kuzzleio/rabbitmq
  ports:
    - "61613:61613"
    - "1883:1883"
    - "5672:5672"
    - "15672:15672"

redis:
  image: redis:3.0.2

elasticsearch:
  image: elasticsearch:1.5.2

logstash:
  image: logstash:1.5.2
  links:
    - elasticlogstash:elasticsearch
  volumes:
    - "../config/perf/logstash.conf:/config-dir/logstash.conf"
  volumes_from:
    - kuzzle
  command: logstash -f /config-dir/logstash.conf
  ports:
    - "61614:61614"

elasticlogstash:
  image: elasticsearch:1.7.0
  command: elasticsearch -Des.cluster.name=elasticlogstash
  ports:
    - "9200:9200"

kibana:
  image: kibana:4.1.1
  links:
    - elasticlogstash:elasticsearch
  ports:
    - "5601:5601"
