kuzzle:
  image: kuzzleio/kuzzle
  command: /run-test-travis.sh
  volumes:
    - "..:/var/app"
  ports:
    - "7512:7512"
    - "7513:7513"
  links:
    - rabbit
    - elasticsearch
    - redis
  environment:
    - LIKE_A_VIRGIN=1
    - FIXTURES
    - MQ_BROKER_ENABLED=1
    - FEATURE_COVERAGE=1
    # Travis env var must be propagated into the container
    - TRAVIS
    - TRAVIS_COMMIT
    - TRAVIS_JOB_NUMBER
    - TRAVIS_BRANCH
    - TRAVIS_JOB_ID
    - TRAVIS_PULL_REQUEST
    - TRAVIS_REPO_SLUG

rabbit:
  image: kuzzleio/rabbitmq

redis:
  image: redis:3.0.2

elasticsearch:
  image: elasticsearch:1.5.2
