kuzzle:
  image: kuzzleio/test
  command: /run-test-travis.sh
  volumes:
    - "..:/var/app"
  links:
    - rabbit
    - elasticsearch
    - redis
  environment:
    - LIKE_A_VIRGIN=1
    - DEFAULT_MAPPING
    - MQ_BROKER_ENABLED=1
    - FEATURE_COVERAGE=1
    - FIXTURES=/var/app/features/fixtures/empty.json
    # Travis env var must be propagated into the container
    - TRAVIS
    - TRAVIS_COMMIT
    - TRAVIS_JOB_NUMBER
    - TRAVIS_BRANCH
    - TRAVIS_JOB_ID
    - TRAVIS_PULL_REQUEST
    - TRAVIS_REPO_SLUG

rabbit:
  image: kuzzleio/rabbitmq

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.2
