kuzzle:
  image: kuzzleio/kuzzle
  command: /run-test.sh
  volumes:
    - "..:/var/app"
  ports:
    - "7511:7511"
    - "7512:7512"
  links:
    - rabbit
    - elasticsearch
    - redis
  environment:
    - LIKE_A_VIRGIN=1
    - DEFAULT_MAPPING
    - FIXTURES=/var/app/features/fixtures/functionalTestsFixtures.json
    - MQ_BROKER_ENABLED=1
    - FEATURE_COVERAGE=1

rabbit:
  image: kuzzleio/rabbitmq
  ports:
    - "61613:61613"
    - "1883:1883"
    - "5672:5672"
    - "15672:15672"

redis:
  image: redis:3.0

elasticsearch:
  image: elasticsearch:1.7
