proxy:
  image: kuzzleio/proxy:alpine
  ports:
    - "7511:7511"
    - "7512:7512"

kuzzle:
  image: kuzzleio/test:alpine
  command: /run-test-travis.sh
  volumes:
    - "..:/var/app"
  links:
    - rabbit
    - elasticsearch
    - redis
    - proxy
  environment:
    - MQ_BROKER_ENABLED=1
    - FEATURE_COVERAGE=1
    # Travis env var must be propagated into the container
    - TRAVIS
    - TRAVIS_COMMIT
    - TRAVIS_JOB_NUMBER
    - TRAVIS_BRANCH
    - TRAVIS_JOB_ID
    - TRAVIS_PULL_REQUEST
    - TRAVIS_REPO_SLUG

rabbit:
  image: kuzzleio/rabbitmq:alpine

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.2
